# Generated by Django 4.0.5 on 2023-11-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littlelemonAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='persons',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='tableno',
        ),
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_guests',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
